In [136]:
import numpy as np 
import pandas as pd 
import seaborn as sns

In [137]:
data=pd.read_csv("EmployeeAttrition1.csv")

In [138]:
data.head()

Education JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0        College           High         2            1102              5993.0   
1  Below College         Medium         2             279              5130.0   
2        College         Medium         1            1373              2090.0   
3         Master           High         1            1392              2909.0   
4  Below College           High         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

  PerformanceRating Attrition  
0         Excellent       Yes  
1       Outstanding        No  
2         Excellent       Yes  
3         Excellent        No  
4         Excellent        No

In [139]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 14 columns):
Education                  1470 non-null object
JobInvolvement             1466 non-null object
JobLevel                   1470 non-null int64
DailyRate(USD)             1470 non-null int64
MonthlyIncome(USD)         1466 non-null float64
NoofCompaniesWorked        1470 non-null int64
TotalWorkingYears          1470 non-null int64
YearsAtCompany             1470 non-null int64
YearsInCurrentRole         1470 non-null int64
YearsSinceLastPromotion    1470 non-null int64
YearsWithCurrentManager    1470 non-null int64
TrainingTimesLastYear      1470 non-null int64
PerformanceRating          1470 non-null object
Attrition                  1470 non-null object
dtypes: float64(1), int64(9), object(4)
memory usage: 160.9+ KB


In [140]:
data.isnull().sum()

Education                  0
JobInvolvement             4
JobLevel                   0
DailyRate(USD)             0
MonthlyIncome(USD)         4
NoofCompaniesWorked        0
TotalWorkingYears          0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrentManager    0
TrainingTimesLastYear      0
PerformanceRating          0
Attrition                  0
dtype: int64

In [141]:
data['MonthlyIncome(USD)']=data['MonthlyIncome(USD)'].fillna(data['MonthlyIncome(USD)'].median())

In [142]:
data

Education JobInvolvement  JobLevel  DailyRate(USD)  \
0           College           High         2            1102   
1     Below College         Medium         2             279   
2           College         Medium         1            1373   
3            Master           High         1            1392   
4     Below College           High         1             591   
5           College           High         1            1005   
6          Bachelor      Very High         1            1324   
7     Below College           High         1            1358   
8          Bachelor            NaN         3             216   
9          Bachelor           High         2            1299   
10         Bachelor      Very High         1             809   
11          College         Medium         2             153   
12    Below College           High         1             670   
13          College           High         1            1346   
14         Bachelor         Medium         1             103   
15           Master      Very High         3            1389   
16          College      Very High         1             334   
17          College      Very High         1            1123   
18           Master         Medium         4            1219   
19         Bachelor           High         1             371   
20          College      Very High         2             673   
21           Master         Medium         1            1218   
22           Master            NaN         3             419   
23          College           High         1             391   
24    Below College           High         1             699   
25         Bachelor           High         5            1282   
26    Below College            NaN         1            1125   
27           Master           High         2             691   
28           Master            NaN         3             477   
29           Master           High         5             705   
...             ...            ...       ...             ...   
1440        College           High         2             688   
1441         Master           High         2             667   
1442         Master           High         1            1092   
1443       Bachelor           High         5             300   
1444        College           High         1             310   
1445         Master         Medium         4             582   
1446       Bachelor         Medium         2             704   
1447         Master            Low         2             301   
1448       Bachelor         Medium         2             930   
1449       Bachelor           High         1             529   
1450         Master           High         3            1146   
1451        College           High         2             345   
1452         Master           High         2             878   
1453         Master         Medium         2            1120   
1454       Bachelor           High         2             374   
1455         Master         Medium         1            1322   
1456         Master           High         2            1199   
1457         Master           High         1            1194   
1458         Master            Low         1             287   
1459        College         Medium         2            1378   
1460         Master         Medium         1             468   
1461       Bachelor         Medium         3             410   
1462  Below College         Medium         4             722   
1463       Bachelor           High         2             325   
1464       Bachelor         Medium         1            1167   
1465        College      Very High         2             884   
1466  Below College         Medium         3             613   
1467       Bachelor      Very High         2             155   
1468       Bachelor         Medium         2            1023   
1469       Bachelor      Very High         2             628   

      MonthlyIncome(USD)  NoofCompaniesWo

In [143]:
data['JobInvolvement'].value_counts()

High         867
Medium       373
Very High    144
Low           82
Name: JobInvolvement, dtype: int64

In [144]:
print(data['JobInvolvement'].value_counts())
data['JobInvolvement']=data['JobInvolvement'].replace(['High','Medium','Very High','Low'],[0,2,3,1])
print(data['JobInvolvement'].value_counts())

High         867
Medium       373
Very High    144
Low           82
Name: JobInvolvement, dtype: int64
0.0    867
2.0    373
3.0    144
1.0     82
Name: JobInvolvement, dtype: int64


In [145]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['JobInvolvement'].value_counts())
data['JobInvolvement']=le.fit_transform(data['JobInvolvement'])
print(data['JobInvolvement'].value_counts())

0.0    867
2.0    373
3.0    144
1.0     82
Name: JobInvolvement, dtype: int64
0    867
2    373
3    144
1     82
7      1
6      1
5      1
4      1
Name: JobInvolvement, dtype: int64


In [146]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  \
0        College               0         2            1102   
1  Below College               2         2             279   
2        College               2         1            1373   
3         Master               0         1            1392   
4  Below College               0         1             591   

   MonthlyIncome(USD)  NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  \
0              5993.0                    8                  8               6   
1              5130.0                    1                 10              10   
2              2090.0                    6                  7               0   
3              2909.0                    1                  8               8   
4              3468.0                    9                  6               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrentManager  \
0                   4                        0                        5   
1                   7                        1                        7   
2                   0                        0                        0   
3                   7                        3                        0   
4                   2                        2                        2   

   TrainingTimesLastYear PerformanceRating Attrition  
0                      0         Excellent       Yes  
1                      3       Outstanding        No  
2                      3         Excellent       Yes  
3                      3         Excellent        No  
4                      3         Excellent        No

In [147]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['Education'].value_counts())
data['Education']=le.fit_transform(data['Education'])
print(data['Education'].value_counts())

Bachelor         572
Master           398
College          282
Below College    170
Doctor            48
Name: Education, dtype: int64
0    572
4    398
2    282
1    170
3     48
Name: Education, dtype: int64


In [148]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0          2               0         2            1102              5993.0   
1          1               2         2             279              5130.0   
2          2               2         1            1373              2090.0   
3          4               0         1            1392              2909.0   
4          1               0         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

  PerformanceRating Attrition  
0         Excellent       Yes  
1       Outstanding        No  
2         Excellent       Yes  
3         Excellent        No  
4         Excellent        No

In [149]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['JobInvolvement'].value_counts())
data['JobInvolvement']=le.fit_transform(data['JobInvolvement'])
print(data['JobInvolvement'].value_counts())

0    867
2    373
3    144
1     82
7      1
6      1
5      1
4      1
Name: JobInvolvement, dtype: int64
0    867
2    373
3    144
1     82
7      1
6      1
5      1
4      1
Name: JobInvolvement, dtype: int64


In [150]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0          2               0         2            1102              5993.0   
1          1               2         2             279              5130.0   
2          2               2         1            1373              2090.0   
3          4               0         1            1392              2909.0   
4          1               0         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

  PerformanceRating Attrition  
0         Excellent       Yes  
1       Outstanding        No  
2         Excellent       Yes  
3         Excellent        No  
4         Excellent        No

In [151]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['PerformanceRating'].value_counts())
data['PerformanceRating']=le.fit_transform(data['PerformanceRating'])
print(data['PerformanceRating'].value_counts())

Excellent      1244
Outstanding     226
Name: PerformanceRating, dtype: int64
0    1244
1     226
Name: PerformanceRating, dtype: int64


In [152]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0          2               0         2            1102              5993.0   
1          1               2         2             279              5130.0   
2          2               2         1            1373              2090.0   
3          4               0         1            1392              2909.0   
4          1               0         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

   PerformanceRating Attrition  
0                  0       Yes  
1                  1        No  
2                  0       Yes  
3                  0        No  
4                  0        No

In [153]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
print(data['Attrition'].value_counts())
data['Attrition']=le.fit_transform(data['Attrition'])
print(data['Attrition'].value_counts())

No     1233
Yes     237
Name: Attrition, dtype: int64
0    1233
1     237
Name: Attrition, dtype: int64


In [154]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0          2               0         2            1102              5993.0   
1          1               2         2             279              5130.0   
2          2               2         1            1373              2090.0   
3          4               0         1            1392              2909.0   
4          1               0         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

   PerformanceRating  Attrition  
0                  0          1  
1                  1          0  
2                  0          1  
3                  0          0  
4                  0          0

In [155]:
data.shape

(1470, 14)

In [156]:
x2=data.iloc[:,[0,2,4,5,11,12]]
x2.head()

Education  JobLevel  MonthlyIncome(USD)  NoofCompaniesWorked  \
0          2         2              5993.0                    8   
1          1         2              5130.0                    1   
2          2         1              2090.0                    6   
3          4         1              2909.0                    1   
4          1         1              3468.0                    9   

   TrainingTimesLastYear  PerformanceRating  
0                      0                  0  
1                      3                  1  
2                      3                  0  
3                      3                  0  
4                      3                  0

In [157]:
y=data.iloc[:,[13]]
y.head()

Attrition
0          1
1          0
2          1
3          0
4          0

In [158]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x2,y,test_size=0.2,random_state=0)

In [159]:
print(x_train.shape)
print(x_test.shape)

(1176, 6)
(294, 6)


In [160]:
print(y_train.shape)
print(y_test.shape)

(1176, 1)
(294, 1)


In [213]:
from sklearn.feature_selection import mutual_info_classif
mi=mutual_info_classif(x_train,y_train)
mi

C:\Users\Darsana\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0.        , 0.02799173, 0.04094992, 0.01332475, 0.        ,
       0.        ])

In [162]:
MI=pd.Series(mi)
MI.index=x_train.columns
MI.sort_values(ascending=False)

MonthlyIncome(USD)       0.041341
JobLevel                 0.025070
Education                0.019036
TrainingTimesLastYear    0.005870
PerformanceRating        0.000000
NoofCompaniesWorked      0.000000
dtype: float64

In [163]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [164]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [165]:
y_pred=lr.predict(x_test)
y_pred[:5]

array([[0.05619646],
       [0.17863361],
       [0.15255455],
       [0.03410831],
       [0.19292511]])

In [166]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

-23.064123036059392

In [167]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(x_train,y_train)

C:\Users\Darsana\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Darsana\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [168]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [169]:
y_pred=logr.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 0])

In [170]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_pred,y_test)

array([[245,  49],
       [  0,   0]], dtype=int64)

In [171]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91       294
           1       0.00      0.00      0.00         0

    accuracy                           0.83       294
   macro avg       0.50      0.42      0.45       294
weighted avg       1.00      0.83      0.91       294



C:\Users\Darsana\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [172]:
from sklearn.linear_model import LogisticRegression
logrunder=LogisticRegression()
logrunder.fit(x_train,y_train)

C:\Users\Darsana\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Darsana\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [173]:
y_pred=logrunder.predict(x_test)
y_pred[:5]


array([0, 0, 0, 0, 0])

In [174]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [175]:
y_pred=dtc.predict(x_test)

In [176]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [177]:
accuracy_score(y_pred,y_test)

0.7448979591836735

In [178]:
confusion_matrix(y_pred,y_test)

array([[208,  38],
       [ 37,  11]], dtype=int64)

In [179]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       245
           1       0.23      0.22      0.23        49

    accuracy                           0.74       294
   macro avg       0.54      0.54      0.54       294
weighted avg       0.74      0.74      0.74       294



In [180]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
dtr.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [181]:
y_pred=dtr.predict(x_test)

In [182]:
y_pred[:5]

array([0., 0., 0., 0., 1.])

In [183]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [184]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

-0.8234128693255232

In [185]:
y_pred_train=dtr.predict(x_train)
r2_score(y_pred_train,y_train)

1.0

In [186]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

C:\Users\Darsana\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Darsana\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [187]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [189]:
y_pred=rfc.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 0])

In [190]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test,y_pred)

0.8129251700680272

In [191]:
confusion_matrix(y_test,y_pred)

array([[235,  10],
       [ 45,   4]], dtype=int64)

In [192]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.96      0.90       245
           1       0.29      0.08      0.13        49

    accuracy                           0.81       294
   macro avg       0.56      0.52      0.51       294
weighted avg       0.75      0.81      0.77       294



In [193]:
from sklearn.ensemble import RandomForestRegressor

In [194]:
rfc=RandomForestRegressor()

In [195]:
rfc.fit(x_train,y_train)

C:\Users\Darsana\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Darsana\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [196]:
from sklearn.metrics import r2_score

In [197]:
yu=rfc.predict(x_test)

In [198]:
r2_score(yu,y_test)

-2.470319634703196

In [199]:
y_pred_train=rfc.predict(x_train)
r2_score(y_train,y_pred_train)

0.8018304763545525

In [200]:
from sklearn.neighbors import KNeighborsClassifier 
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

C:\Users\Darsana\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [201]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [202]:
y_pred=knn.predict(x_test)
y_pred[:5]

array([0, 0, 0, 0, 0])

In [203]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8061224489795918

In [204]:
y_train_pred=knn.predict(x_train)
y_train_pred[:5]

array([0, 0, 0, 0, 1])

In [205]:
accuracy_score(y_train,y_train_pred)

0.8537414965986394

In [206]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_test,y_pred)
print(confusion_matrix)

[[236   9]
 [ 48   1]]


In [207]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_train,y_train_pred)
print(confusion_matrix)

[[970  18]
 [154  34]]


In [208]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89       245
           1       0.10      0.02      0.03        49

    accuracy                           0.81       294
   macro avg       0.47      0.49      0.46       294
weighted avg       0.71      0.81      0.75       294



In [209]:
from sklearn.model_selection import GridSearchCV
grid_param={
    'criterion':['gini','entropy'],'max_depth': [1,2,3]
}
grid_search=GridSearchCV(estimator=dtc,param_grid=grid_param,cv=5,n_jobs=-1)
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3]},
             pre_dispatch='2*

In [210]:
grid_search.best_params_

{'criterion': 'gini', 'max_depth': 1}

In [211]:
dtc_hyper=DecisionTreeClassifier(criterion='gini',max_depth=1)
dtc_hyper.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [212]:
y_pred_hyper=dtc_hyper.predict(x_test)
accuracy_score(y_test,y_pred_hyper)

0.8333333333333334